name: Auto update

on:
  # runs every hour
  schedule:
    - cron: "0 * * * *"
  # allow manually trigger
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'jonz94/homebrew-sarasa-nerd-fonts'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_PERSONAL_ACCESS_TOKEN }}
      - name: Magic 😎
        run: |
          # Find the latest version
          LATEST_VERSION=$(curl -fsSL "https://api.github.com/repos/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/latest" | grep tag_name | cut -d '"' -f 4 | cut -d v -f 2)
          echo Latest version of jonz94/Sarasa-Gothic-Nerd-Fonts is ${LATEST_VERSION}

          # Find the current version
          CURRENT_VERSION=$(grep "version \"" Casks/font-sarasa-mono-tc-nerd-font.rb | cut -d\" -f 2)
          echo Current version of jonz94/homebrew-sarasa-nerd-fonts is ${CURRENT_VERSION}

          if [[ "$LATEST_VERSION" == "$CURRENT_VERSION" ]]; then
            echo Everything is up to date!
            exit 0
          fi

          bash developer/bin/generate_cask

          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "🤖 ci: update from ${CURRENT_VERSION} to ${LATEST_VERSION}"
          git push
